lexik_translation_grid:
    path:     /grid
    defaults: { _controller: "LexikTranslationBundle:Edition:grid" }

lexik_translation_list:
    path:     /list
    defaults: { _controller: "LexikTranslationBundle:Edition:list" }

lexik_translation_update:
    path:         /update
    defaults:     { _controller: "LexikTranslationBundle:Edition:update" }
    requirements: { _method: POST }

lexik_translation_new:
    path:     /new
    defaults: { _controller: "LexikTranslationBundle:Edition:new" }

lexik_translation_invalidate_cache:
    path:     /invalidate-cache
    defaults: { _controller: "LexikTranslationBundle:Edition:invalidateCache" }
